### ISSUE TITLE
the upload component can't work in latest vaddin 12.0.0

### ISSUE THREAD

**Issue by limonte** [vaadin/vaadin-upload-flow#104] opened 2018-12-10 08:03 UTC
_From @jessyZu on December 9, 2018 2:57_

when upgrade to 12.0.0,the upload component can't listen the event.
code:
```
 MultiFileMemoryBuffer buffer = new MultiFileMemoryBuffer();
        upload.setReceiver(buffer);
        upload.setAcceptedFileTypes("image/jpeg", "image/png", "image/gif", "image/jpg");
        upload.addSucceededListener(event -> {
            try {
                String imgName = MD5Util.md5(UUID.randomUUID().toString()) + "." + event.getFileName().split("\\.")[1];
                FileUtils.writeByteArrayToFile(new File("/statics/imgs/" + imgName),
                        IOUtils.toByteArray(buffer.getInputStream(event.getFileName())));
                getModel().getImgs().add(imgName);

            } catch (Exception e) {
                getLogger().error("upload error", e);
                showNotification("图片保存失败："+e.getMessage(),true);

            }
        });


```

_Copied from original issue: vaadin/vaadin-upload#294_

**Comment by heruan** [comment] 2018-12-10 08:34
@jessyZu Are you using Spring? If so, probably related to https://github.com/vaadin/spring/issues/381

**Comment by benderfzi** [comment] 2018-12-10 10:18
[Bender-Vaadin12-Spring-Issue-104.zip](https://github.com/vaadin/vaadin-upload-flow/files/2662673/Bender-Vaadin12-Spring-Issue-104.zip)

Attached minimum example which reproduces the error with Spring Boot and Vaadin 12.

**Comment by heruan** [comment] 2018-12-10 10:24
This is a duplicate of #103, better to close this and follow-up there.

**Comment by limonte** [comment] 2018-12-10 11:12
Thank you @heruan 

duplicate fo #103

**Closed** 2018-12-10 11:12 UTC
