### ISSUE TITLE
Provide a method to re-enable component after successful upload

### ISSUE THREAD

**Issue by tarekoraby** [vaadin/vaadin-upload-flow#175] opened 2020-07-15 13:06 UTC
Currently, once a file is uploaded successfully, the Upload button will be automatically disabled. This might be fine as the default behavior. However, the component's API doesn't allow one to re-enable the upload button after that, thereby it precludes use cases that require allowing users to use the same component to upload several files. It would, thus, be nice to provide such functionality some future release.

**Comment by mheicke** [comment] 2020-07-15 13:25
Alternatively it would be great to be able to set custom errors which then would then show the error message and enable the retry or cancel buttons on the right like this: 

<img width="519" alt="Bildschirmfoto 2020-07-15 um 13 23 14" src="https://user-images.githubusercontent.com/246571/87550482-5bcd9e80-c6af-11ea-8190-018df872b41d.png">

**Comment by alvarezguille** [comment] 2020-07-21 10:44
Closing as a duplicate of #96
Check the workaround in this comment https://github.com/vaadin/vaadin-upload-flow/issues/96#issuecomment-472744475

**Closed by alvarezguille** 2020-07-21 10:44 UTC
