### ISSUE TITLE
Upload doesn't accept new files after page is refreshed with @PreserveOnRefresh

### ISSUE THREAD

**Issue by anasmi** [vaadin/vaadin-upload-flow#154] opened 2019-11-04 07:37 UTC
Version platform : 14.0.10

Code to reproduce:

```@PreserveOnRefresh
@Route("uploadpreserve")
public class UploadPreserveOnRefresh extends VerticalLayout {

    public UploadPreserveOnRefresh(){
        MemoryBuffer buffer = new MemoryBuffer();
        Upload upload=new Upload(buffer);
        add(upload);
    }
}
```

After uploading a file and then refreshing a page and trying to upload anything else `Forbidden` message is displayed and upload is not started

**Comment by web-padawan** [comment] 2019-11-04 07:55
Thanks for the issue. Seems to be a duplicate of #147, let's continue discussing it there.

**Closed by web-padawan** 2019-11-04 07:55 UTC
