### ISSUE TITLE
vaadin-upload doesn't work with vaadin12.0.2

### ISSUE THREAD

**Issue by limonte** [vaadin/vaadin-upload-flow#108] opened 2018-12-28 11:08 UTC
_From @KrifaYounes on December 28, 2018 11:1_

nothing happens when we upload a file 

listener doesn't work (vaadin 12.0.2)
```
uploadFileButton.addFinishedListener(event -> {
            InputStream
});
```

_Copied from original issue: vaadin/vaadin-upload#297_

**Comment by masbaehr** [comment] 2018-12-30 10:04
Any workaround yet? This is a big blocker..

**Comment by ttsanton** [comment] 2019-01-02 13:51
I have also found that the Upload also isn't working with 13.0.0.alpha1

**Comment by mstahv** [comment] 2019-01-04 13:55
I guess this is duplicate to https://github.com/vaadin/vaadin-upload-flow/issues/77 ? My workaround has been to use succeeded listener instead of finished listener.

**Comment by ttsanton** [comment] 2019-01-04 13:58
I have found that the SucceededListener does not respond either, though.

**Comment by mstahv** [comment] 2019-01-04 14:43
Weird, do you have a project where this can be reproduced? Or using Spring (IIRC there was some additional dependency or bean that needed to be there as a temporary workaround for Uoload) ?

**Comment by ttsanton** [comment] 2019-01-04 15:12
The project I am working on does not use Spring.

Here is a basic Upload w/listeners that I created to double check what I already had implemented in other portions of my project - none of the listeners return the print statements. I tried both with and without the use of the MemoryBuffer, and the listeners are still not responding.

```
MemoryBuffer buffer = new MemoryBuffer();
Upload imgUpload = new Upload(buffer);

add(imgUpload);

imgUpload.addStartedListener(e -> {
     System.out.println("Handling upload of " + e.getFileName() 
             + " (" + e.getContentLength() + " bytes) started");
});
imgUpload.addFinishedListener(e -> {
     System.out.println("Handling upload of " + e.getFileName() 
             + " (" + e.getContentLength() + " bytes) finished");
});
imgUpload.addSucceededListener(e -> {
     System.out.println("Succeeded Upload of " + e.getFileName());		     
});	}
```

**Comment by mstahv** [comment] 2019-01-06 10:35
Plain servlet (like @ttsanton), tried with jetty maven plugin, but I'd be surprised if that is the issue.

@masbaehr was your issue only the non-fired finished event or something else? That don't fire for me neither, nowhere, but there is already another issue for that case #77. If there is no other issue with Upload, I think we should close this as duplicate.

**Comment by masbaehr** [comment] 2019-01-06 10:43
For me the succeed event does not work either.. It simply doesn't do anything. Also i noticed that the file is actually not being uploaded from the browser. E.g i tried to upload a 112KB file:

![image](https://user-images.githubusercontent.com/38694044/50735023-43222580-11a8-11e9-9640-90b8a4463c67.png)

**Comment by mstahv** [comment] 2019-01-06 11:02
Any chance you could reduce the problem a bit, share it in GitHub (or as zip attachement here) and also let us know which browser you are using. It is pretty much impossible to get this solved if our engineers can't reproduce the issue.

**Comment by masbaehr** [comment] 2019-01-06 11:58
[vaadin-github.zip](https://github.com/vaadin/vaadin-upload-flow/files/2730423/vaadin-github.zip)

This project reproduces the problem (Can be built easily using vscode)

**Comment by mstahv** [comment] 2019-01-06 12:53
Ah, so you are using Spring Boot -> another Vaadin upload issue 😤

The workaround is to add following configuration to your src/main/resources/application.properties file:

    spring.servlet.multipart.enabled = false

See issue https://github.com/vaadin/spring/issues/381 for more details.

Let me know if you can make it work now!

**Comment by masbaehr** [comment] 2019-01-06 12:58
Yea thanks - i can confirm this solves the issue, but as the last guy mentioned - it would disable multipart upload in regular @WebServlet 

Also the Vaadin Version does not make a difference, i tried all Versions from 10.0.9 to 12.0.3.

**Comment by mstahv** [comment] 2019-01-06 13:02
Yep, but definitely vaadin-spring issue, not vaadin-upload-flow. Closing as duplicate to https://github.com/vaadin/spring/issues/381

**Closed by mstahv** 2019-01-06 13:02 UTC
Labels: duplicate

**Comment by ttsanton** [comment] 2019-01-07 17:23
After reading your comments about Spring, I did some investigating on the project I am working on, which uses Shiro as the security framework. It looks like that is related to the issues I am having with the Upload. After some trial-and-error, I have found that implementing the security features in the project causes the Listeners/Buffer for the Upload to not work as expected.

**Comment by mstahv** [comment] 2019-01-08 10:46
If you can reduce an example project that you can share, it might help others to look into it too. It might be something that needs to be configured in Shiro or something that we could improve in Vaadin Upload, but anyways that would probably be helpful for somebody else too. If you think there is something to do in vaadin-upload-flow, create a new issue and attach your test project there.
