### ISSUE TITLE
File chooser dialog not showing up on mobile device

### ISSUE THREAD

**Issue by lolytxd** [vaadin/vaadin-upload-flow#61] opened 2018-06-27 10:45 UTC
Vaadin version: 10.0.0
Device with Android, Chrome mobile browser.

### Description
Sometimes after pressing the "Select file" button nothing happens, sometimes file chooser opens after some time. I have checked it on few devices.

### Steps to reproduce
Go to page [https://vaadin.com/components/vaadin-upload/java-examples](https://vaadin.com/components/vaadin-upload/java-examples) and try few times to upload file.

**Comment by web-padawan** [comment] 2020-02-14 12:15
> when the app swicthes to camer it reload the page after going back to web page.

I can not reproduce this on Android 7.0 with "Open Device Camera" [web component demo](https://cdn.vaadin.com/vaadin-upload/4.2.2/demo/#upload-basic-demos).


Closing as duplicate of vaadin/vaadin-upload#277 which is fixed.

**Closed by web-padawan** 2020-02-14 12:15 UTC
Labels: awaits another ticket, bug
